# Generated by Django 5.2 on 2025-05-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_admin_table_basket_person_stuff_delete_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produckt',
            old_name='cost',
            new_name='price',
        ),
        migrations.AddField(
            model_name='produckt',
            name='category',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produckt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produckts/'),
        ),
    ]
