# Generated by Django 5.2 on 2025-05-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_cost_produckt_price_produckt_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produckt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/main/images/admin_add'),
        ),
    ]
