# Generated by Django 5.2 on 2025-05-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_produckt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produckt',
            name='new',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produckt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/images/admin_add'),
        ),
    ]
