# Generated by Django 5.2 on 2025-05-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_produckt_new_alter_produckt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
    ]
