# Generated by Django 5.2 on 2025-05-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_person_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='produckt',
            name='rewiew',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
