# Generated by Django 5.2 on 2025-05-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_produckt_rewiew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produckt',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
