# Generated by Django 5.2 on 2025-05-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rewiew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produckt',
            name='rewiew',
        ),
        migrations.AddField(
            model_name='rewiew',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produckt',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
