# Generated by Django 5.2 on 2025-06-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produckt',
            name='new',
        ),
    ]
